import Layout from '../components/layout'
import Table from '../components/table'
import TableRow from '../components/tableRow'
import TableHeader from '../components/tableHeader'
import TableData from '../components/tableData'
import TableContent from '../components/tableContent'
import TableHeaderContent from '../components/tableHeaderContent'

function Test() {
  return (
    <Layout>
      <Table>
        <TableHeaderContent>
          <TableRow>
            <TableHeader>
              Foo
            </TableHeader>
            <TableHeader>
              Bar
            </TableHeader>
          </TableRow>
        </TableHeaderContent>
        <TableContent>
          <TableRow>
            <TableData>
              c
            </TableData>
            <TableData>
              d
            </TableData>
          </TableRow>
          <TableRow>
            <TableData>
              c
            </TableData>
            <TableData>
              d
            </TableData>
          </TableRow>
          <TableRow>
            <TableData>
              c
            </TableData>
            <TableData>
              d
            </TableData>
          </TableRow>
          <TableRow>
            <TableData>
              c
            </TableData>
            <TableData>
              d
            </TableData>
          </TableRow>
          <TableRow>
            <TableData>
              c
            </TableData>
            <TableData>
              d
            </TableData>
          </TableRow>
          <TableRow>
            <TableData>
              c
            </TableData>
            <TableData>
              d
            </TableData>
          </TableRow>
          <TableRow>
            <TableData>
              c
            </TableData>
            <TableData>
              d
            </TableData>
          </TableRow>
          <TableRow>
            <TableData>
              c
            </TableData>
            <TableData>
              d
            </TableData>
          </TableRow>
          <TableRow>
            <TableData>
              c
            </TableData>
            <TableData>
              d
            </TableData>
          </TableRow>
          <TableRow>
            <TableData>
              c
            </TableData>
            <TableData>
              d
            </TableData>
          </TableRow>
          <TableRow>
            <TableData>
              c
            </TableData>
            <TableData>
              d
            </TableData>
          </TableRow>
          <TableRow>
            <TableData>
              c
            </TableData>
            <TableData>
              d
            </TableData>
          </TableRow>
          <TableRow>
            <TableData>
              c
            </TableData>
            <TableData>
              d
            </TableData>
          </TableRow>
          <TableRow>
            <TableData>
              c
            </TableData>
            <TableData>
              d
            </TableData>
          </TableRow>
        </TableContent>
      </Table>
    </Layout>
  )
}

export default Test
