/**
 * Renders the hosted-apps list into dist/index.html at build time.
 *
 * Reads dist/apps.json (generated by generate-manifest.ts) plus each app's
 * manifest.json for its icon, then replaces the marker block inside
 * <div id="app"> with static markup — so the list ships in the HTML
 * instead of being fetched and rendered after load.
 *
 * Usage:
 *   deno run --allow-read --allow-write scripts/render-index.ts
 *   deno task render-index
 */

const indexPath = "./dist/index.html";
const appsJsonPath = "./dist/apps.json";
const START = "<!-- apps:start -->";
const END = "<!-- apps:end -->";

interface AppMeta {
  id: string;
  name: string;
  description: string;
  path: string;
}

function esc(s: string): string {
  return s
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&#39;");
}

async function resolveIcon(app: AppMeta): Promise<string> {
  const base = app.path; // e.g., /apps/rummytimer/
  try {
    const raw = await Deno.readTextFile(`./dist/apps/${app.id}/manifest.json`);
    const manifest = JSON.parse(raw);
    const src = manifest?.icons?.[0]?.src;
    if (typeof src === "string" && src.length > 0) {
      if (src.startsWith("/")) return src;
      if (src.startsWith("./")) return base + src.slice(2);
      return base + src;
    }
  } catch {
    // no manifest or no icons — fall through to known filename
  }
  return `${base}favicon.svg`;
}

function fallbackOnError(base: string): string {
  return (
    `(function(i){var f=['hex.svg','favicon.svg','icon.svg'];` +
    `var c=i.src.split('/').pop();var n=f.indexOf(c);` +
    `if(n!==-1&&n+1<f.length){i.src='${base}'+f[n+1];}` +
    `else if(!i.src.endsWith('favicon.svg')){i.src='${base}favicon.svg';}})(this)`
  );
}

async function renderCard(app: AppMeta): Promise<string[]> {
  const href = esc(app.path);
  const id = esc(app.id);
  const name = esc(app.name);
  const desc = esc(app.description);
  const title = esc(app.description || app.name);
  const icon = esc(await resolveIcon(app));
  const onerror = esc(fallbackOnError(app.path));

  const lines = [
    `    <a class="app-card" href="${href}" data-app-id="${id}" title="${title}">`,
    `      <img class="app-icon" src="${icon}" alt="${name} icon" loading="lazy" onerror="${onerror}" />`,
    `      <div class="app-text">`,
    `        <span class="app-name">${name}</span>`,
  ];
  if (app.description) {
    lines.push(`        <small class="app-desc">${desc}</small>`);
  }
  lines.push(`      </div>`, `    </a>`);
  return lines;
}

async function renderApps(apps: AppMeta[]): Promise<string> {
  const lines = [
    `<section class="apps-section">`,
    `  <nav class="apps-nav" aria-label="Hosted applications">`,
  ];
  if (apps.length === 0) {
    lines.push(`    <p class="apps-empty">No apps available.</p>`);
  } else {
    for (const app of apps) {
      lines.push(...await renderCard(app));
    }
  }
  lines.push(`  </nav>`, `</section>`);
  return lines.join("\n");
}

async function main(): Promise<void> {
  let apps: AppMeta[] = [];
  try {
    const manifest = JSON.parse(await Deno.readTextFile(appsJsonPath));
    apps = Array.isArray(manifest.apps) ? manifest.apps : [];
  } catch (e) {
    console.error(`Failed to read ${appsJsonPath} (run generate-manifest.ts first):`, e);
    Deno.exit(1);
  }

  let html: string;
  try {
    html = await Deno.readTextFile(indexPath);
  } catch (e) {
    console.error(`Failed to read ${indexPath} (run the copy step first):`, e);
    Deno.exit(1);
  }

  const startIdx = html.indexOf(START);
  const endIdx = html.indexOf(END, startIdx + START.length);
  if (startIdx === -1 || endIdx === -1) {
    console.error(`${indexPath} is missing the ${START} ... ${END} marker block`);
    Deno.exit(1);
  }

  const block = `${START}\n${await renderApps(apps)}\n    ${END}`;
  const out = html.slice(0, startIdx) + block + html.slice(endIdx + END.length);
  await Deno.writeTextFile(indexPath, out);
  console.log(`Rendered ${apps.length} app(s) into ${indexPath}: ${apps.map((a) => a.id).join(", ")}`);
}

if (import.meta.main) {
  await main();
}
